test

diff --git a/.github/workflows/ss.yml b/.github/workflows/ss.yml
--- a/.github/workflows/ss.yml
+++ b/.github/workflows/ss.yml
@@ -29,21 +29,21 @@ jobs:
       - name: Wait for App to Start
         run: sleep 5s
 
-      - name: Run Autocannon Load Test
-        run: npx autocannon -c 10 -d 5 -p 10 -j http://localhost:8181 | jq '.["requests"]["average"]'
-        env:
-          GITHUB_OUTPUT: ${{ steps.server.outputs.pid }}
-
-      - name: Get Autocannon output
-        run: echo "${{ steps.autocannon.outputs.stdout }}"
-        id: autocannon_output
-
-      - name: Check Autocannon Avg
+      - name: Run Autocannon load test
         run: |
-          if (( $(echo "$avg < 10000" | bc -l) )); then
-          echo "Autocannon Avg is less than 10000"
-          exit 1
+          node /autocannon/index.js
+          if (( $(echo "$GITHUB_OUTPUT < 10000" | bc -l) )); then
+            echo "Load test failed"
+            kill $APP_PID
+            exit 1
+          else
+            echo "Load test passed"
+            kill $APP_PID
+            exit 0
           fi
+        env:
+          APP_URL: http://localhost:8181
+          GITHUB_OUTPUT: $(node /path/to/script.js | grep Avg | awk '{print $2}')
 
       - name: Stop Go App
         run: pkill app
